config/routes.rb
Movietmins::Application.routes.draw do

  resources :users
  resources :movies
  resources :reviews, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews
	validates :name,  presence: true, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 300 }
	validates :movie_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :edit, :update]
  before_action :admin_user,     only: [:destroy]

  def new
  	@movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      flash[:success] = "success!"
      redirect_to @movie
    else
      render 'new'
    end
  end

  def show
  	@movie = Movie.find(params[:id])
    @reviews = @movie.reviews.paginate(page: params[:page])
    @review = @movie.reviews.build if signed_in?
  end

  def index
  	 @movies = Movie.paginate(page: params[:page])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
  end

  def destroy
    Movie.find(params[:id]).destroy
    flash[:success] = "Movie deleted."
    redirect_to movies_url   
  end

  private

    def movie_params
      params.require(:movie).permit(:name, :length, :director, :cast, :genre)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def signed_in?
      !current_user.nil?
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :signed_in_user

  def create
    @review = current_movie.reviews.build(review_params)
    if @review.save
      flash[:success] = "Review posted!"
      redirect_to movie_path(@current_movie)
    else
      flash.now[:error] = "Error! Failed to create review."
      @movies = Movie.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

    def review_params
      params.require(:review).permit(:content)
    end

    def current_movie
      @current_movie = Movie.find_by(params[:id])
    end

    def current_movie=(movie)
      @current_movie = movie
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  	  @movies = Movie.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Movietmins"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    movietmins.com
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.amctheatres.com/">New Movies</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "movietmins", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>

            <li><%= link_to "Movies", movies_path %></li> 

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<% provide(:title, 'All movies') %>
<h1>All movies</h1>

<%= will_paginate %>

<ul class="movies">
	<% @movies.each do |movie| %>
    <li>
      <%= link_to movie.name, movie %>
      	  <% if current_user.admin? && !current_user?(@user) %>
	      | <%= link_to "delete", movie, method: :delete,
	                                    data: { confirm: "You sure?" } %>
	    <% end %>
    </li>
 <% end %>
</ul>

<%= will_paginate %>

app/views/movies/new.html.erb
<% provide(:title, 'Create movie') %>
<h1>Create a new movie</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@movie) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :length %>
      <%= f.text_field :length %>

      <%= f.label :director %>
      <%= f.text_field :director %>

      <%= f.label :cast %>
      <%= f.text_field :cast %>

      <%= f.label :genre %>
      <%= f.text_field :genre %>

      <%= f.submit "Create new movie", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<% provide(:title, @movie.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @movie.name %>
      </h1>
      <h2>
        <%= @movie.length %> mins
        <br>
        <%= @movie.genre %>
        <br> 
        Director: <%= @movie.director %>
        <br>
        Cast: <%= @movie.cast %>
      <h2>
    </section>

    <section>
        <%= render 'shared/review_form' %>
    </section>
    
  </aside>
   <div class="span8">
    <% if @movie.reviews.any? %>
      <h3>Reviews (<%= @movie.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<li>
  <span class="content"><%= review.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
  </span>
</li>

app/views/reviews/new.html.erb
<% provide(:title, @movie.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @movie.name %>
      </h1>
      <h2>
        <%= @movie.length %> mins
        <br>
        <%= @movie.genre %>
        <br> 
        Director: <%= @movie.director %>
        <br>
        Cast: <%= @movie.cast %>
      <h2>
    </section>

    <section>
        <%= render 'shared/review_form' %>
    </section>
    
  </aside>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_movie_form.html.erb
 <%= form_for(Movie.new) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :length %>
      <%= f.text_field :length %>

      <%= f.label :director %>
      <%= f.text_field :director %>

      <%= f.label :cast %>
      <%= f.text_field :cast %>

      <%= f.label :genre %>
      <%= f.text_field :genre %>

      <%= f.submit "Create new movie", class: "btn btn-small btn-success" %>
    <% end %>

app/views/shared/_movie_list.html.erb
<ul class="movies">
	<% @movies.each do |movie| %>
    <li>
      <%= link_to movie.name, movie %>
    </li>
 <% end %>
</ul>

app/views/shared/_review_form.html.erb
<%= form_for(@review) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new review..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-success" %>
<% end %>

app/views/static_pages/about.html.erb
    <% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      The movietmins.com is a website allows users to rate and write reviews for movies. 
      <br>
      Here each signed-up user has a profile to see all reviews and rating they posted.
      <br>
      It also has a list of all movie that you can find. Each movie has its own profile listing all the reviews users wrote and the overall score of a movie.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact administrater of movietmins.com at: admin@movietmins.com.
</p>

app/views/static_pages/help.html.erb
    <% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Get help on movietmins.com by sending an email to help@movietmins.com.
    </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <h1>
          <%= current_user.name %>
        </h1>
        <span>
          <%= link_to "view my profile", current_user %>
        </span>
      </section>
      <section>
        <%= render 'shared/movie_form' %>
      </section>
    </aside>
  <div class="span8">
      <h3>Lastest movies</h3>
      <%= render 'shared/movie_list' %>
    </div>
  </div>

<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Movietmins</h1>
    <h2>
        Going to the movie theater? <br>
        Check out the reviews on movietmins!
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>